# Generated by Django 4.0.3 on 2022-03-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=256)),
                ('correct_answer', models.CharField(max_length=256)),
                ('wrong_answer1', models.CharField(max_length=256)),
                ('wrong_answer2', models.CharField(max_length=256)),
                ('wrong_answer3', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('phone_num', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='Test_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='test',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.test_question'),
        ),
    ]
