# Generated by Django 4.0.3 on 2022-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question_bank',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, to='tests.question'),
        ),
        migrations.DeleteModel(
            name='Test_Question',
        ),
    ]
