# Generated by Django 4.0.3 on 2022-03-12 21:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_test_question_bank_test_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecuted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tests.test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
