# Generated by Django 4.0.3 on 2022-03-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_answer_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maketest',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='maketest',
            name='test_ptr',
        ),
        migrations.AddField(
            model_name='student',
            name='executed_tests',
            field=models.ManyToManyField(blank=True, to='tests.testexecuted'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='MakeTest',
        ),
    ]
