# Generated by Django 4.0.3 on 2022-03-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_maketest_answers_remove_maketest_test_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='executed_tests',
        ),
    ]
