# Generated by Django 4.0.3 on 2022-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_student_executed_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tests_done',
            field=models.ManyToManyField(to='tests.testexecuted'),
        ),
    ]
