# Generated by Django 4.0.3 on 2022-03-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_student_tests_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tests_done',
        ),
    ]
